// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: gRPCProto/gRPCDemo.proto

package grpcdemopb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Numbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartingValue int32 `protobuf:"varint,1,opt,name=startingValue,proto3" json:"startingValue,omitempty"`
	EndingValue   int32 `protobuf:"varint,2,opt,name=endingValue,proto3" json:"endingValue,omitempty"`
}

func (x *Numbers) Reset() {
	*x = Numbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Numbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Numbers) ProtoMessage() {}

func (x *Numbers) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Numbers.ProtoReflect.Descriptor instead.
func (*Numbers) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{0}
}

func (x *Numbers) GetStartingValue() int32 {
	if x != nil {
		return x.StartingValue
	}
	return 0
}

func (x *Numbers) GetEndingValue() int32 {
	if x != nil {
		return x.EndingValue
	}
	return 0
}

type CalculationUnaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number *Numbers `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *CalculationUnaryRequest) Reset() {
	*x = CalculationUnaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationUnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationUnaryRequest) ProtoMessage() {}

func (x *CalculationUnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationUnaryRequest.ProtoReflect.Descriptor instead.
func (*CalculationUnaryRequest) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationUnaryRequest) GetNumber() *Numbers {
	if x != nil {
		return x.Number
	}
	return nil
}

type CalculationUnaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculationUnaryResponse) Reset() {
	*x = CalculationUnaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationUnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationUnaryResponse) ProtoMessage() {}

func (x *CalculationUnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationUnaryResponse.ProtoReflect.Descriptor instead.
func (*CalculationUnaryResponse) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{2}
}

func (x *CalculationUnaryResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ServerStreamCalculationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number *Numbers `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *ServerStreamCalculationRequest) Reset() {
	*x = ServerStreamCalculationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamCalculationRequest) ProtoMessage() {}

func (x *ServerStreamCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamCalculationRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamCalculationRequest) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{3}
}

func (x *ServerStreamCalculationRequest) GetNumber() *Numbers {
	if x != nil {
		return x.Number
	}
	return nil
}

type ServerStreamCalculationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ServerStreamCalculationResponse) Reset() {
	*x = ServerStreamCalculationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamCalculationResponse) ProtoMessage() {}

func (x *ServerStreamCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamCalculationResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamCalculationResponse) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamCalculationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ClientStreamCalculationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *ClientStreamCalculationRequest) Reset() {
	*x = ClientStreamCalculationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamCalculationRequest) ProtoMessage() {}

func (x *ClientStreamCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamCalculationRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamCalculationRequest) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{5}
}

func (x *ClientStreamCalculationRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ClientStreamCalculationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ClientStreamCalculationResponse) Reset() {
	*x = ClientStreamCalculationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamCalculationResponse) ProtoMessage() {}

func (x *ClientStreamCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamCalculationResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamCalculationResponse) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{6}
}

func (x *ClientStreamCalculationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type BiDirectionalStreamCalculationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *BiDirectionalStreamCalculationRequest) Reset() {
	*x = BiDirectionalStreamCalculationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiDirectionalStreamCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDirectionalStreamCalculationRequest) ProtoMessage() {}

func (x *BiDirectionalStreamCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDirectionalStreamCalculationRequest.ProtoReflect.Descriptor instead.
func (*BiDirectionalStreamCalculationRequest) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{7}
}

func (x *BiDirectionalStreamCalculationRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BiDirectionalStreamCalculationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BiDirectionalStreamCalculationResponse) Reset() {
	*x = BiDirectionalStreamCalculationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiDirectionalStreamCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDirectionalStreamCalculationResponse) ProtoMessage() {}

func (x *BiDirectionalStreamCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPCProto_gRPCDemo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDirectionalStreamCalculationResponse.ProtoReflect.Descriptor instead.
func (*BiDirectionalStreamCalculationResponse) Descriptor() ([]byte, []int) {
	return file_gRPCProto_gRPCDemo_proto_rawDescGZIP(), []int{8}
}

func (x *BiDirectionalStreamCalculationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_gRPCProto_gRPCDemo_proto protoreflect.FileDescriptor

var file_gRPCProto_gRPCDemo_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x52, 0x50, 0x43,
	0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x52, 0x50, 0x43,
	0x44, 0x65, 0x6d, 0x6f, 0x22, 0x51, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x32, 0x0a,
	0x18, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x4b, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x39,
	0x0a, 0x1f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x38, 0x0a, 0x1e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x1f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3f,
	0x0a, 0x25, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x40, 0x0a, 0x26, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0xeb, 0x03, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x67, 0x52, 0x50, 0x43,
	0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67,
	0x52, 0x50, 0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x75, 0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x28, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x52, 0x50,
	0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x75, 0x0a, 0x1a, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65,
	0x6d, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x12, 0x8c, 0x01, 0x0a, 0x21, 0x62, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65, 0x6d,
	0x6f, 0x2e, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x44, 0x65,
	0x6d, 0x6f, 0x2e, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPCProto_gRPCDemo_proto_rawDescOnce sync.Once
	file_gRPCProto_gRPCDemo_proto_rawDescData = file_gRPCProto_gRPCDemo_proto_rawDesc
)

func file_gRPCProto_gRPCDemo_proto_rawDescGZIP() []byte {
	file_gRPCProto_gRPCDemo_proto_rawDescOnce.Do(func() {
		file_gRPCProto_gRPCDemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPCProto_gRPCDemo_proto_rawDescData)
	})
	return file_gRPCProto_gRPCDemo_proto_rawDescData
}

var file_gRPCProto_gRPCDemo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gRPCProto_gRPCDemo_proto_goTypes = []interface{}{
	(*Numbers)(nil),                                // 0: gRPCDemo.Numbers
	(*CalculationUnaryRequest)(nil),                // 1: gRPCDemo.CalculationUnaryRequest
	(*CalculationUnaryResponse)(nil),               // 2: gRPCDemo.CalculationUnaryResponse
	(*ServerStreamCalculationRequest)(nil),         // 3: gRPCDemo.ServerStreamCalculationRequest
	(*ServerStreamCalculationResponse)(nil),        // 4: gRPCDemo.ServerStreamCalculationResponse
	(*ClientStreamCalculationRequest)(nil),         // 5: gRPCDemo.ClientStreamCalculationRequest
	(*ClientStreamCalculationResponse)(nil),        // 6: gRPCDemo.ClientStreamCalculationResponse
	(*BiDirectionalStreamCalculationRequest)(nil),  // 7: gRPCDemo.BiDirectionalStreamCalculationRequest
	(*BiDirectionalStreamCalculationResponse)(nil), // 8: gRPCDemo.BiDirectionalStreamCalculationResponse
}
var file_gRPCProto_gRPCDemo_proto_depIdxs = []int32{
	0, // 0: gRPCDemo.CalculationUnaryRequest.number:type_name -> gRPCDemo.Numbers
	0, // 1: gRPCDemo.ServerStreamCalculationRequest.number:type_name -> gRPCDemo.Numbers
	1, // 2: gRPCDemo.additionService.unaryCalculation:input_type -> gRPCDemo.CalculationUnaryRequest
	3, // 3: gRPCDemo.additionService.serverStreamingCalculation:input_type -> gRPCDemo.ServerStreamCalculationRequest
	5, // 4: gRPCDemo.additionService.clientStreamingCalculation:input_type -> gRPCDemo.ClientStreamCalculationRequest
	7, // 5: gRPCDemo.additionService.biDirectionalStreamingCalculation:input_type -> gRPCDemo.BiDirectionalStreamCalculationRequest
	2, // 6: gRPCDemo.additionService.unaryCalculation:output_type -> gRPCDemo.CalculationUnaryResponse
	4, // 7: gRPCDemo.additionService.serverStreamingCalculation:output_type -> gRPCDemo.ServerStreamCalculationResponse
	6, // 8: gRPCDemo.additionService.clientStreamingCalculation:output_type -> gRPCDemo.ClientStreamCalculationResponse
	8, // 9: gRPCDemo.additionService.biDirectionalStreamingCalculation:output_type -> gRPCDemo.BiDirectionalStreamCalculationResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gRPCProto_gRPCDemo_proto_init() }
func file_gRPCProto_gRPCDemo_proto_init() {
	if File_gRPCProto_gRPCDemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPCProto_gRPCDemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Numbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationUnaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationUnaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamCalculationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamCalculationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamCalculationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamCalculationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiDirectionalStreamCalculationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPCProto_gRPCDemo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiDirectionalStreamCalculationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPCProto_gRPCDemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPCProto_gRPCDemo_proto_goTypes,
		DependencyIndexes: file_gRPCProto_gRPCDemo_proto_depIdxs,
		MessageInfos:      file_gRPCProto_gRPCDemo_proto_msgTypes,
	}.Build()
	File_gRPCProto_gRPCDemo_proto = out.File
	file_gRPCProto_gRPCDemo_proto_rawDesc = nil
	file_gRPCProto_gRPCDemo_proto_goTypes = nil
	file_gRPCProto_gRPCDemo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdditionServiceClient is the client API for AdditionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdditionServiceClient interface {
	//Unary API Example
	//This is the most common API we use in everyday life.
	//The client sends a request for server performs the required action and thr server then sends a response.
	UnaryCalculation(ctx context.Context, in *CalculationUnaryRequest, opts ...grpc.CallOption) (*CalculationUnaryResponse, error)
	//Server Streaming
	//In Server streaming we send some data to the server and server sends the processed data back to us
	//in stream. The client does not have to wait for server to send the data after complete action.
	ServerStreamingCalculation(ctx context.Context, in *ServerStreamCalculationRequest, opts ...grpc.CallOption) (AdditionService_ServerStreamingCalculationClient, error)
	//Client Streaming
	//In Client streaming the client sends the information to server in stream. This is useful when we have to send large
	//data to server. By sending data in stream we can ignore multiple calls to the server.
	ClientStreamingCalculation(ctx context.Context, opts ...grpc.CallOption) (AdditionService_ClientStreamingCalculationClient, error)
	//Bi-Directional Streaming
	//In this streaming methods we can send data to server in streams and receive response from server in streams.
	//This is usefull in getting real-time values based on inputs.
	BiDirectionalStreamingCalculation(ctx context.Context, opts ...grpc.CallOption) (AdditionService_BiDirectionalStreamingCalculationClient, error)
}

type additionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdditionServiceClient(cc grpc.ClientConnInterface) AdditionServiceClient {
	return &additionServiceClient{cc}
}

func (c *additionServiceClient) UnaryCalculation(ctx context.Context, in *CalculationUnaryRequest, opts ...grpc.CallOption) (*CalculationUnaryResponse, error) {
	out := new(CalculationUnaryResponse)
	err := c.cc.Invoke(ctx, "/gRPCDemo.additionService/unaryCalculation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *additionServiceClient) ServerStreamingCalculation(ctx context.Context, in *ServerStreamCalculationRequest, opts ...grpc.CallOption) (AdditionService_ServerStreamingCalculationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdditionService_serviceDesc.Streams[0], "/gRPCDemo.additionService/serverStreamingCalculation", opts...)
	if err != nil {
		return nil, err
	}
	x := &additionServiceServerStreamingCalculationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdditionService_ServerStreamingCalculationClient interface {
	Recv() (*ServerStreamCalculationResponse, error)
	grpc.ClientStream
}

type additionServiceServerStreamingCalculationClient struct {
	grpc.ClientStream
}

func (x *additionServiceServerStreamingCalculationClient) Recv() (*ServerStreamCalculationResponse, error) {
	m := new(ServerStreamCalculationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *additionServiceClient) ClientStreamingCalculation(ctx context.Context, opts ...grpc.CallOption) (AdditionService_ClientStreamingCalculationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdditionService_serviceDesc.Streams[1], "/gRPCDemo.additionService/clientStreamingCalculation", opts...)
	if err != nil {
		return nil, err
	}
	x := &additionServiceClientStreamingCalculationClient{stream}
	return x, nil
}

type AdditionService_ClientStreamingCalculationClient interface {
	Send(*ClientStreamCalculationRequest) error
	CloseAndRecv() (*ClientStreamCalculationResponse, error)
	grpc.ClientStream
}

type additionServiceClientStreamingCalculationClient struct {
	grpc.ClientStream
}

func (x *additionServiceClientStreamingCalculationClient) Send(m *ClientStreamCalculationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *additionServiceClientStreamingCalculationClient) CloseAndRecv() (*ClientStreamCalculationResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientStreamCalculationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *additionServiceClient) BiDirectionalStreamingCalculation(ctx context.Context, opts ...grpc.CallOption) (AdditionService_BiDirectionalStreamingCalculationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdditionService_serviceDesc.Streams[2], "/gRPCDemo.additionService/biDirectionalStreamingCalculation", opts...)
	if err != nil {
		return nil, err
	}
	x := &additionServiceBiDirectionalStreamingCalculationClient{stream}
	return x, nil
}

type AdditionService_BiDirectionalStreamingCalculationClient interface {
	Send(*BiDirectionalStreamCalculationRequest) error
	Recv() (*BiDirectionalStreamCalculationResponse, error)
	grpc.ClientStream
}

type additionServiceBiDirectionalStreamingCalculationClient struct {
	grpc.ClientStream
}

func (x *additionServiceBiDirectionalStreamingCalculationClient) Send(m *BiDirectionalStreamCalculationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *additionServiceBiDirectionalStreamingCalculationClient) Recv() (*BiDirectionalStreamCalculationResponse, error) {
	m := new(BiDirectionalStreamCalculationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdditionServiceServer is the server API for AdditionService service.
type AdditionServiceServer interface {
	//Unary API Example
	//This is the most common API we use in everyday life.
	//The client sends a request for server performs the required action and thr server then sends a response.
	UnaryCalculation(context.Context, *CalculationUnaryRequest) (*CalculationUnaryResponse, error)
	//Server Streaming
	//In Server streaming we send some data to the server and server sends the processed data back to us
	//in stream. The client does not have to wait for server to send the data after complete action.
	ServerStreamingCalculation(*ServerStreamCalculationRequest, AdditionService_ServerStreamingCalculationServer) error
	//Client Streaming
	//In Client streaming the client sends the information to server in stream. This is useful when we have to send large
	//data to server. By sending data in stream we can ignore multiple calls to the server.
	ClientStreamingCalculation(AdditionService_ClientStreamingCalculationServer) error
	//Bi-Directional Streaming
	//In this streaming methods we can send data to server in streams and receive response from server in streams.
	//This is usefull in getting real-time values based on inputs.
	BiDirectionalStreamingCalculation(AdditionService_BiDirectionalStreamingCalculationServer) error
}

// UnimplementedAdditionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdditionServiceServer struct {
}

func (*UnimplementedAdditionServiceServer) UnaryCalculation(context.Context, *CalculationUnaryRequest) (*CalculationUnaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryCalculation not implemented")
}
func (*UnimplementedAdditionServiceServer) ServerStreamingCalculation(*ServerStreamCalculationRequest, AdditionService_ServerStreamingCalculationServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamingCalculation not implemented")
}
func (*UnimplementedAdditionServiceServer) ClientStreamingCalculation(AdditionService_ClientStreamingCalculationServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingCalculation not implemented")
}
func (*UnimplementedAdditionServiceServer) BiDirectionalStreamingCalculation(AdditionService_BiDirectionalStreamingCalculationServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDirectionalStreamingCalculation not implemented")
}

func RegisterAdditionServiceServer(s *grpc.Server, srv AdditionServiceServer) {
	s.RegisterService(&_AdditionService_serviceDesc, srv)
}

func _AdditionService_UnaryCalculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationUnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServiceServer).UnaryCalculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPCDemo.additionService/UnaryCalculation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServiceServer).UnaryCalculation(ctx, req.(*CalculationUnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdditionService_ServerStreamingCalculation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamCalculationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdditionServiceServer).ServerStreamingCalculation(m, &additionServiceServerStreamingCalculationServer{stream})
}

type AdditionService_ServerStreamingCalculationServer interface {
	Send(*ServerStreamCalculationResponse) error
	grpc.ServerStream
}

type additionServiceServerStreamingCalculationServer struct {
	grpc.ServerStream
}

func (x *additionServiceServerStreamingCalculationServer) Send(m *ServerStreamCalculationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AdditionService_ClientStreamingCalculation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdditionServiceServer).ClientStreamingCalculation(&additionServiceClientStreamingCalculationServer{stream})
}

type AdditionService_ClientStreamingCalculationServer interface {
	SendAndClose(*ClientStreamCalculationResponse) error
	Recv() (*ClientStreamCalculationRequest, error)
	grpc.ServerStream
}

type additionServiceClientStreamingCalculationServer struct {
	grpc.ServerStream
}

func (x *additionServiceClientStreamingCalculationServer) SendAndClose(m *ClientStreamCalculationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *additionServiceClientStreamingCalculationServer) Recv() (*ClientStreamCalculationRequest, error) {
	m := new(ClientStreamCalculationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AdditionService_BiDirectionalStreamingCalculation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdditionServiceServer).BiDirectionalStreamingCalculation(&additionServiceBiDirectionalStreamingCalculationServer{stream})
}

type AdditionService_BiDirectionalStreamingCalculationServer interface {
	Send(*BiDirectionalStreamCalculationResponse) error
	Recv() (*BiDirectionalStreamCalculationRequest, error)
	grpc.ServerStream
}

type additionServiceBiDirectionalStreamingCalculationServer struct {
	grpc.ServerStream
}

func (x *additionServiceBiDirectionalStreamingCalculationServer) Send(m *BiDirectionalStreamCalculationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *additionServiceBiDirectionalStreamingCalculationServer) Recv() (*BiDirectionalStreamCalculationRequest, error) {
	m := new(BiDirectionalStreamCalculationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AdditionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gRPCDemo.additionService",
	HandlerType: (*AdditionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "unaryCalculation",
			Handler:    _AdditionService_UnaryCalculation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "serverStreamingCalculation",
			Handler:       _AdditionService_ServerStreamingCalculation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "clientStreamingCalculation",
			Handler:       _AdditionService_ClientStreamingCalculation_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "biDirectionalStreamingCalculation",
			Handler:       _AdditionService_BiDirectionalStreamingCalculation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gRPCProto/gRPCDemo.proto",
}
